use_frameworks!

target 'SwiftExtension_Example' do
  pod 'SwiftExtension', :path => '../'

  target 'SwiftExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
